Use writeClosure instead of writeReferencesToFile
The latter was deprecated in nix 24.11:

    error: writeReferencesToFile has been removed. Use writeClosure instead.